### ISSUE TITLE
client side capabilities

### ISSUE THREAD

**Issue by gedw99** [medama-io/medama#100]
Can I get the client side capabilities ?

It owed be highly useful. see: https://webplatform.github.io/docs/concepts/Detecting_device_and_browser/

for example Navigator.webShare, etc.  

Tis requires a simple js on the sites.

**Comment by ayuhito** [comment]
Thanks for making this suggestion! 

I don't think we want to support this feature as we want to avoid collecting excessive fingerprinting data due to our nature as privacy-oriented product. You may need to find an alternative project that supports that instead.

**Comment by ayuhito** [comment]
Thanks for your understanding and sorry!
