### ISSUE TITLE
Show the website name

### ISSUE THREAD

**Issue by rolikeusch** [medama-io/medama#78]
Would be great to see the website name in the statistic page.

![IMG_0003](https://github.com/medama-io/medama/assets/3592156/c4a923c8-3893-4952-954a-b3fdfef6bb5b)

**Comment by ayuhito** [comment]
Thanks for the feedback! I was planning on adding a quick switcher dropdown instead to make that more functional. Thoughts?

![image](https://github.com/medama-io/medama/assets/38220115/be554681-57d6-41de-9e53-300f2447b315)

**Comment by rolikeusch** [comment]
That looks good.
