### ISSUE TITLE
Add arm64 support to docker image

### ISSUE THREAD

**Issue by jwr1** [medama-io/medama#89]
At the moment, the docker image only supports amd64; it would be great if it also supported arm64.

**Comment by marsavela** [comment]
Here for this too. 

>  ⠋ medama The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by ayuhito** [comment]
Hi! I added ARM docker images to the build process. Can you test the latest commit using `ghcr.io/medama-io/medama:edge` to verify if that works? If everything is good, I can publish a new `latest` tagged version with a couple other improvements in a day or two.

**Comment by ayuhito** [comment]
Hi! Can you try out the latest commit using `ghcr.io/medama-io/medama:edge`? If it works, I can push a new `latest` version tag in a couple of days.

**Comment by marsavela** [comment]
@ayuhito Works as expected for me. This is for a RaspberryPi. 👍

**Comment by jwr1** [comment]
Yup, worked great for me too :rocket:.
